flowchart TD
    A[Investigation]

    A --> B[People]
    A --> C[Vehicles]
    A --> D[Organisations]
    A --> E[Document Management]

    A --> F[Links]

    F --> G[Research Investigation Information]
    F --> H[Link to Existing METIS Record]
    F --> I[Create New METIS Record]