flowchart TD
    A[Links]

    A --> B[Investigation]
    A --> C[People]
    A --> D[Vehicles]
    A --> E[Organisations]
    A --> F[Documents]

    C --> C1[John Doe]
    C1 --> C2[Comms]
    C2 --> C3[077777775450]
    C2 --> C4["example@email.com"]

    D --> D1[AB12 CDE]

    E --> E1[Example Organisation]