flowchart TD
    A[John Doe]

    A --> B[Personal Information]
    A --> C[Comms]
    A --> D[Address]
    A --> E[Vehicle]

    C --> C1[077777775450]
    C --> C2["example@email.com"]

    D --> D1[21 Example Street]

    E --> E1[AB12 CDE]