flowchart LR
    A[Links]

    A --> B[John Doe]
    A --> C[Comms:077777775450]
    A --> D[Vehicle AB12 CDE]

    B --> E[View / Edit / Research]
    C --> F[View / Edit / Research]
    D --> G[View / Edit / Research]